
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// BUYER
export const CREATE_BUYER_SUCCESS = "CREATE_BUYER_SUCCESS";
export const DELETE_BUYER_SUCCESS = "DELETE_BUYER_SUCCESS";
export const FINDBY_BUYERTRANSACTION_BUYER_SUCCESS = "FINDBY_BUYERTRANSACTION_BUYER_SUCCESS";
export const GET_BUYER_SUCCESS = "GET_BUYER_SUCCESS";
export const LIST_BUYER_SUCCESS = "LIST_BUYER_SUCCESS";
export const UPDATE_BUYER_SUCCESS = "UPDATE_BUYER_SUCCESS";
export const VALIDATE_BUYER_SUCCESS = "VALIDATE_BUYER_SUCCESS";

// PRODUCT
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const LIST_PRODUCT_SUCCESS = "LIST_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";

// TRANSACTION
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const FINDBY_PRODUCTTRANSACTION_TRANSACTION_SUCCESS = "FINDBY_PRODUCTTRANSACTION_TRANSACTION_SUCCESS";
export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS";
export const LIST_TRANSACTION_SUCCESS = "LIST_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
